export const TOKEN_JWT = "web_qlns_token_jwt";

export const GET_LIST_CONTACT = "GET_LIST_CONTACT";
export const GET_LIST_DEPARTMENT = "GET_LIST_DEPARTMENT";
export const GET_LIST_LEVEL = "GET_LIST_LEVEL";
export const GET_LIST_POSITION = "GET_LIST_POSITION";
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_SPECIALIZED = "GET_LIST_SPECIALIZED";
export const GET_STAFF_INFO = "GET_STAFF_INFO";
export const GET_TIME_SHEET = "GET_TIME_SHEET";
export const GET_REQUEST_LIST = "GET_REQUEST_LIST";
export const GET_LIST_STAFF = "GET_LIST_STAFF";

export const QUERY_LIST_MANAGER = "QUERY_LIST_MANAGER";
export const QUERY_SPECIALIZED_LIST = "QUERY_SPECIALIZED_LIST";
export const QUERY_POSITION_LIST = "QUERY_POSITION_LIST";
export const QUERY_LEVEL_LIST = "QUERY_SPECIALIZED_LIST";
export const QUERY_DEPARTMENT_LIST = "QUERY_DEPARTMENT_LIST";
